### ISSUE TITLE
Error launching ephys-align

### ISSUE THREAD

**Issue by emarcoss** [int-brain-lab/neuropixels_course_2024#7]
I am trying to launch ephys-align, but I get the following error:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/iblenv/bin/ephys-align", line 8, in <module>
    sys.exit(launch_offline())
             ^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/iblenv/lib/python3.11/site-packages/atlaselectrophysiology/ephys_atlas_gui.py", line 2155, in launch_offline
    mainapp_off = MainWindow(offline=True)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/iblenv/lib/python3.11/site-packages/atlaselectrophysiology/ephys_atlas_gui.py", line 65, in __init__
    self.loaddata = LoadDataLocal()
                    ^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/iblenv/lib/python3.11/site-packages/atlaselectrophysiology/load_data_local.py", line 22, in __init__
    self.brain_atlas = atlas.AllenAtlas(25)
                       ^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/iblenv/lib/python3.11/site-packages/iblatlas/atlas.py", line 1388, in __init__
    image = self._read_volume(hist_path)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/iblenv/lib/python3.11/site-packages/iblatlas/atlas.py", line 1395, in _read_volume
    volume, _ = nrrd.read(file_volume, index_order='C')  # ml, dv, ap
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/iblenv/lib/python3.11/site-packages/nrrd/reader.py", line 517, in read
    data = read_data(header, fh, filename, index_order)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/iblenv/lib/python3.11/site-packages/nrrd/reader.py", line 463, in read_data
    raise NRRDError(f'Size of the data does not equal the product of all the dimensions: '
nrrd.errors.NRRDError: Size of the data does not equal the product of all the dimensions: 77045760-63588509=13457251

I have a Mac OS.
Do you know why? Any help will be appreciated!
Thanks.

**Comment by mayofaulkner** [comment]
Hello,

It looks like the histology files that are needed did not download properly. Could you please do the following
In a terminal type `conda activate iblenv` and launch an ipython prompt `ipython`

In the python terminal copy this code
```python
import one.params
from pathlib import Path
import shutil
cache_dir = Path(one.params.get(silent=True).CACHE_DIR).joinpath('histology')
if cache_dir.exists():
    shutil.rmtree(cache_dir)
```

Can you then relaunching the GUI as per the original instructions. 

Let me know if that helps!

**Comment by emarcoss** [comment]
It works! Thanks.
